syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "resource/common.proto";

service AdminUserLogic {
  rpc ShowAdminUsersTotalByFiltersWithSortersPagination(AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) returns (AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput);
  rpc AddAminUser(AdminUserAddAminUserInput) returns (AdminUserAddAminUserOutput);
  rpc EditAdminUserById(AdminUserEditAdminUserByIdInput) returns (AdminUserEditAdminUserByIdOutput);
}

message AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput {
  repeated pb.resource.AdminUser admin_users = 1;
  uint64 total = 2;
}

message AdminUserVariable {
  optional string name = 1;
  optional string password = 2;
  repeated uint32 admin_role_ids = 3; // repeated 本身語意就是可以是空的，不用也不能標。
}

message AdminUserAddAminUserInput {
  AdminUserVariable variable = 1;
}

message AdminUserAddAminUserOutput {}

message AdminUserEditAdminUserByIdInput {
  AdminUserVariable variable = 1;
  uint32 id = 2;
}

message AdminUserEditAdminUserByIdOutput {}
