syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "resource/common.proto";

service AdminPermissionGroupLogic {
  rpc AddAdminPermissionGroup(AdminPermissionGroupAddAdminPermissionGroupInput) returns (AdminPermissionGroupAddAdminPermissionGroupOutput);
  rpc ShowTree(AdminPermissionGroupShowTreeInput) returns (AdminPermissionGroupShowTreeOutput);
  rpc ShowAdminPermissionGroupById(AdminPermissionGroupShowAdminPermissionGroupByIdInput) returns (AdminPermissionGroupShowAdminPermissionGroupByIdOutput);
  rpc ShowAdminPermissionGroups(AdminPermissionGroupShowAdminPermissionGroupsInput) returns (AdminPermissionGroupShowAdminPermissionGroupsOutput);
  rpc ShowAdminPermissionGroupsTotalByFiltersWithSortersPagination(AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationInput) returns (AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationOutput);
}

message AdminPermissionGroupValue {
  optional string key = 1;
  optional string name = 2;
}

message AdminPermissionGroupAddAdminPermissionGroupInput {
  AdminPermissionGroupValue value = 1;
}

message AdminPermissionGroupAddAdminPermissionGroupOutput {
  bool status = 1;
}

message AdminPermissionGroupShowTreeInput {

}

message AdminPermissionGroupShowTreeOutput {
  repeated pb.resource.AdminPermissionGroup admin_permission_groups = 1;
}

message AdminPermissionGroupShowAdminPermissionGroupByIdInput {
  uint64 id = 1;
}

message AdminPermissionGroupShowAdminPermissionGroupByIdOutput {
  pb.resource.AdminPermissionGroup admin_permission_group = 1;
}

message AdminPermissionGroupShowAdminPermissionGroupsInput {
  
}

message AdminPermissionGroupShowAdminPermissionGroupsOutput {
  repeated pb.resource.AdminPermissionGroup admin_permission_groups = 1;
}

message AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message AdminPermissionGroupShowAdminPermissionGroupsTotalByFiltersWithSortersPaginationOutput {
  repeated pb.resource.AdminPermissionGroup admin_permission_groups = 1;
  uint64 total = 2;
}
