syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "resource/common.proto";

service AdminUserLogic {
  rpc ShowAdminUsersTotalByFiltersWithSortersPagination(AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput) returns (AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput);
  rpc ShowAdminUserById(AdminUserShowAdminUserByIdInput) returns (AdminUserShowAdminUserByIdOutput);

  rpc AddAminUser(AdminUserAddAminUserInput) returns (AdminUserAddAminUserOutput);
  rpc EditAdminUserById(AdminUserEditAdminUserByIdInput) returns (AdminUserEditAdminUserByIdOutput);
  rpc RemoveAdminUserById(AdminUserRemoveAdminUserByIdInput) returns (AdminUserRemoveAdminUserByIdOutput);
}


message AdminUserVariable {
  optional string name = 1;
  optional string password = 2;
  repeated uint64 admin_role_ids = 3; // repeated 本身語意就是可以是空的，不用也不能標。
}

message AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message AdminUserShowAdminUsersTotalByFiltersWithSortersPaginationOutput {
  repeated pb.resource.AdminUser admin_users = 1;
  uint64 total = 2;
}

message AdminUserShowAdminUserByIdInput {
  uint64 id = 2;
}

message AdminUserShowAdminUserByIdOutput{
  repeated pb.resource.AdminUser admin_users = 1;
  uint64 total = 2;
}


message AdminUserAddAminUserInput {
  AdminUserVariable variable = 1;
}

message AdminUserAddAminUserOutput {}

message AdminUserEditAdminUserByIdInput {
  AdminUserVariable variable = 1;
  uint64 id = 2;
}

message AdminUserEditAdminUserByIdOutput {}

message AdminUserRemoveAdminUserByIdInput {
  uint64 id = 1;
}

message AdminUserRemoveAdminUserByIdOutput {}
