syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "common.proto";

service GameTypeLogic {
  rpc ShowTree(GameTypeShowTreeInput) returns (GameTypeShowTreeOutput);
  rpc ShowGameTypeById(GameTypeShowGameTypeByIdInput) returns (GameTypeShowGameTypeByIdOutput);
  rpc ShowGameTypes(GameTypeShowGameTypesInput) returns (GameTypeShowGameTypesOutput);
  rpc ShowGameTypesTotalByFiltersWithSortersPagination(GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput) returns (GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput);
}

message GameTypeShowTreeInput {}

message GameTypeShowTreeOutput {
  repeated pb.resource.GameType game_types = 1;
}

message GameTypeShowGameTypeByIdInput {
  uint64 id = 1;
}

message GameTypeShowGameTypeByIdOutput {
  pb.resource.GameType game_type = 1;
}

message GameTypeShowGameTypesInput {
  
}

message GameTypeShowGameTypesOutput {
  repeated pb.resource.GameType game_types = 1;
}

message GameTypeShowGameTypesTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message GameTypeShowGameTypesTotalByFiltersWithSortersPaginationOutput {
  repeated pb.resource.GameType game_types = 1;
  uint64 total = 2;
}
