syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "common.proto";

service GameLogic {
  rpc ShowGamesTotalByFiltersWithSortersPagination(GameShowGamesTotalByFiltersWithSortersPaginationInput) returns (GameShowGamesTotalByFiltersWithSortersPaginationOutput);

}

message GameShowGamesTotalByFiltersWithSortersPaginationInput {
  repeated pb.Filter filters = 1;
  repeated pb.Sorter sorters = 2;
  pb.Pagination pagination = 3;
}

message GameShowGamesTotalByFiltersWithSortersPaginationOutput {
  repeated pb.Game games = 1;
  uint64 total = 2;
}
