syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "common.proto";

service TableLogic {
  rpc ShowTableById(TableShowTableByIdInput) returns (TableShowTableByIdOutput);
  rpc ShowTablesTotalByFiltersWithSortersPagination(TableShowTablesTotalByFiltersWithSortersPaginationInput) returns (TableShowTablesTotalByFiltersWithSortersPaginationOutput);
}

message TableShowTableByIdInput {
  uint64 id = 1;
}

message TableShowTableByIdOutput {
  pb.Table table = 1;
}

message TableShowTablesTotalByFiltersWithSortersPaginationInput {
  repeated pb.Filter filters = 1;
  repeated pb.Sorter sorters = 2;
  pb.Pagination pagination = 3;
}

message TableShowTablesTotalByFiltersWithSortersPaginationOutput {
  repeated pb.Table tables = 1;
  uint64 total = 2;
}
