syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "google/protobuf/timestamp.proto";
import "resource/logic/game.proto";
import "resource/resource.proto";

service TableLogic {
  rpc ShowTablesTotalByFiltersWithSortersPagination(TableShowTablesTotalByFiltersWithSortersPaginationInput) returns (TableShowTablesTotalByFiltersWithSortersPaginationOutput);
}

message Table {
  uint32 id = 1;
  string no = 2;
  uint32 game_id = 3;
  string key = 4;
  uint32 state = 5;
  string description = 6;
  string result = 7;
  google.protobuf.Timestamp started_at = 8;
  google.protobuf.Timestamp ended_at = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  Game game = 13;
}

message TableShowTablesTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message TableShowTablesTotalByFiltersWithSortersPaginationOutput {
  repeated Table tables = 1;
  uint64 total = 2;
}
