syntax = "proto3";

package pb.resource.logic;

option go_package = "./pb_resource_logic";

import "resource/common.proto";

service TableLogic {
  rpc ShowTablesTotalByFiltersWithSortersPagination(TableShowTablesTotalByFiltersWithSortersPaginationInput) returns (TableShowTablesTotalByFiltersWithSortersPaginationOutput);
}

message TableShowTablesTotalByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message TableShowTablesTotalByFiltersWithSortersPaginationOutput {
  repeated pb.resource.Table tables = 1;
  uint64 total = 2;
}
