syntax = "proto3";

package pb.recognition.ir.inference.game;

option go_package = "./pb_recognition_ir_inference_game";

import "recognition/ir.proto";

service BaccaratService {
  rpc RecognizeItems(BaccaratRecognizeItemsRequest) returns (stream BaccaratRecognizeItemsResponse);
  rpc RecognizeObjects(BaccaratRecognizeObjectsRequest) returns (BaccaratRecognizeObjectsResponse);
  rpc RecognizeAll(BaccaratRecognizeAllRequest) returns (BaccaratRecognizeAllResponse);
}

message BaccaratRecognizeItemsRequest {

}

message BaccaratRecognizeItemsResponse {
  repeated pb.recognition.Poker items = 1;
}

message BaccaratRecognizeObjectsRequest {

}

message BaccaratRecognizeAllRequest {

}

message BaccaratRecognizeObjectsResponse {
  repeated pb.recognition.Object objects = 1;
}

message BaccaratRecognizeAllResponse {
  repeated pb.recognition.Object objects = 1;
  repeated pb.recognition.Poker items = 2;
}
