syntax = "proto3";

package pb.recognition.ir.inference.game;

option go_package = "./pb_recognition_ir_inference_game";

import "recognition/ir.proto";

service SicboService {
  rpc RecognizeItems(SicboRecognizeItemsRequest) returns (stream SicboRecognizeItemsResponse);
  rpc RecognizeObjects(SicboRecognizeObjectsRequest) returns (SicboRecognizeObjectsResponse);
  rpc RecognizeAll(SicboRecognizeAllRequest) returns (SicboRecognizeAllResponse);
}

message SicboRecognizeItemsRequest {

}

message SicboRecognizeItemsResponse {
  repeated pb.recognition.Die items = 1;
}

message SicboRecognizeObjectsRequest {

}

message SicboRecognizeAllRequest {

}

message SicboRecognizeObjectsResponse {
  repeated pb.recognition.Object objects = 1;
}

message SicboRecognizeAllResponse {
  repeated pb.recognition.Object objects = 1;
  repeated pb.recognition.Die items = 2;
}
