syntax = "proto3";

package pb;

option go_package = "example/pb";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  bool encrypted = 50001;
}

message Filter {
  string field = 1;
  string operator = 2;
  google.protobuf.Value value = 3;
}

message Sorter {
  string field = 1;
  string order = 2;
}

message Pagination {
  uint64 size = 1;
  uint64 page = 2;
}

message AdminPermissionGroup {
  uint64 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
  uint64 parent_id = 7;
  AdminPermissionGroup parent = 8;
  repeated AdminPermissionGroup children = 9;
  repeated AdminPermission admin_permissions = 10;
}

message AdminPermissionGroupVariable {
  optional string key = 1;
  optional string name = 2;
  repeated AdminPermissionVariable admin_permissions = 3;
}

message AdminPermissionVariable {
  optional uint64 id = 1;
  optional uint64 type = 2;
  optional string key = 3;
  optional string name = 4;
}

message AdminUserVariable {
  optional string name = 1;
  optional string password = 2 [
    (encrypted) = true
  ];
  repeated uint64 admin_role_ids = 3; // repeated 本身語意就是可以是空的，不用也不能標。
}

message StaffUserVariable {
  string name = 1;
}

message AppUserVariable {
  optional uint64 id = 1;
  optional string name = 2;
  optional string password = 3;
}

message GameVariable {
  optional uint64 game_type_id = 1;
  optional string key = 2;
  optional string name = 3;
  optional string description = 4;
}

message GameTypeVariable {
  optional string key = 1;
  optional string name = 2;
}

message TableVariable {
  optional string no = 1;
  optional uint64 game_id = 2;
  optional string key = 3;
  optional uint64 state = 4;
  optional string description = 5;
  optional string result = 6;
  google.protobuf.Timestamp started_at = 7;
  google.protobuf.Timestamp ended_at = 8;
}



message GameType {
  uint64 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
  uint64 parent_id = 7;
  GameType parent = 8;
  repeated GameType children = 9;
}

message AdminUser {
  uint64 id = 1;
  string name = 2;
  string password = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
  repeated AdminRole admin_roles = 7;
}


message AdminRole {
  uint64 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
}

message AdminRoleVariable {
  optional string key = 1;
  optional string name = 2;
}

message AdminPermission {
  uint64 id = 1;
  uint64 type = 2;
  string key = 3;
  string name = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
  google.protobuf.Timestamp deleted_at = 7;
  uint64 admin_permission_group_id = 8;
}

message AppUser {
  uint64 id = 1;
  string name = 2;
  string password = 3;
  uint64 balance = 4;
}



message Game {
  uint64 id = 1;
  uint64 game_type_id = 2;
  string key = 3;
  string name = 4;
  string description = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  google.protobuf.Timestamp deleted_at = 8;
  GameType game_type = 9;
}



message Table {
  uint64 id = 1;
  string no = 2;
  uint64 game_id = 3;
  string key = 4;
  uint64 state = 5;
  string description = 6;
  string result = 7;
  google.protobuf.Timestamp started_at = 8;
  google.protobuf.Timestamp ended_at = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  Game game = 13;
}

