syntax = "proto3";

package pb.facade;

option go_package = "example/pb/facade;pb_facade";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

message Filter {
  string field = 1;
  string operator = 2;
  google.protobuf.Value value = 3;
}

message Sorter {
  string field = 1;
  string order = 2;
}

message Pagination {
  uint64 size = 1;
  uint64 page = 2;
}

message GameType {
  uint64 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
  uint64 parent_id = 7;
  GameType parent = 8;
  repeated GameType children = 9;
}

message Game {
  uint64 id = 1;
  uint64 game_type_id = 2;
  string key = 3;
  string name = 4;
  string description = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  google.protobuf.Timestamp deleted_at = 8;
  GameType game_type = 9;
}
