syntax = "proto3";

package pb.facade.admin.resource;

option go_package = "./pb_facade_admin_resource";

import "common.proto";

service GameController {
  rpc AddOne(GameAddOneRequest) returns (GameAddOneResponse);
  rpc EditOne(GameEditOneRequest) returns (GameEditOneResponse);
  rpc RemoveOne(GameRemoveOneRequest) returns (GameRemoveOneResponse);
  rpc ShowOne(GameShowOneRequest) returns (GameShowOneResponse);
  rpc ShowOnes(GameShowOnesRequest) returns (GameShowOnesResponse);
}

message GameAddOneRequest {
  pb.GameVariable variable = 1;
}

message GameAddOneResponse {}

message GameEditOneRequest {
  repeated pb.Filter filters = 1;
  pb.GameVariable variable = 2;
}

message GameEditOneResponse {

}

message GameRemoveOneRequest {
  repeated pb.Filter filters = 1;
}

message GameRemoveOneResponse {}

message GameShowOneRequest {
  repeated pb.Filter filters = 1;
}

message GameShowOneResponse {
  pb.Game One = 1;
}

message GameShowOnesRequest {
  repeated pb.Filter filters = 1;
  repeated pb.Sorter sorters = 2;
  pb.Pagination pagination = 3;
}

message GameShowOnesResponse {
  repeated pb.Game Ones = 1;
  uint64 total = 2;
}
