syntax = "proto3";

package pb.facade.admin.resource;

option go_package = "./pb_facade_admin_resource";

import "facade/common.proto";

service GameController {
  rpc AddOne(GameAddOneRequest) returns (GameAddOneResponse);
  rpc EditOne(GameEditOneRequest) returns (GameEditOneResponse);
  rpc RemoveOne(GameRemoveOneRequest) returns (GameRemoveOneResponse);
  rpc ShowOne(GameShowOneRequest) returns (GameShowOneResponse);
  rpc ShowOnes(GameShowOnesRequest) returns (GameShowOnesResponse);
}

message GameValue {
  optional uint64 game_type_id = 1;
  optional string key = 2;
  optional string name = 3;
  optional string description = 4;
}

message GameAddOneRequest {
  GameValue value = 1;
}

message GameAddOneResponse {}

message GameEditOneRequest {
  repeated pb.facade.Filter filters = 1;
  GameValue value = 2;
}

message GameEditOneResponse {}

message GameRemoveOneRequest {
  repeated pb.facade.Filter filters = 1;
}

message GameRemoveOneResponse {}

message GameShowOneRequest {
  repeated pb.facade.Filter filters = 1;
}

message GameShowOneResponse {
  pb.facade.Game One = 1;
}

message GameShowOnesRequest {
  repeated pb.facade.Filter filters = 1;
  repeated pb.facade.Sorter sorters = 2;
  pb.facade.Pagination pagination = 3;
}

message GameShowOnesResponse {
  repeated pb.facade.Game Ones = 1;
  uint64 total = 2;
}
