syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "common.proto";

service AdminUserModel {
  rpc ShowOneByName(AdminUserShowOneByNameInput) returns (AdminUserShowOneByNameOutput);
  rpc ShowOneById(AdminUserShowOneByIdInput) returns (AdminUserShowOneByIdOutput);
  rpc AddOne(AdminUserAddOneInput) returns (AdminUserAddOneOutput);
  rpc EditOneById(AdminUserEditOneByIdInput) returns (AdminUserEditOneByIdOutput);
  rpc RemoveOneById(AdminUserRemoveOneByIdInput) returns (AdminUserRemoveOneByIdOutput);
  rpc ShowOnesByFiltersWithSortersPagination(AdminUserShowOnesByFiltersWithSortersPaginationInput) returns (AdminUserShowOnesByFiltersWithSortersPaginationOutput);
  rpc TotalByFilters(AdminUserTotalByFiltersInput) returns (AdminUserTotalByFiltersOutput);
}

message AdminUserShowOneByNameInput {
  string name = 1;
}

message AdminUserShowOneByNameOutput {
  pb.resource.AdminUser admin_user = 1;
}

// 數據模型直接對ID查找
message AdminUserShowOneByIdInput {
  uint32 id = 1;
}

message AdminUserShowOneByIdOutput {
  pb.resource.AdminUser admin_user = 1;
}

message AdminUserAddOneInput {
  pb.resource.AdminUserVariable variable = 1;
}

message AdminUserAddOneOutput {}

// 數據模型直接對ID查找
message AdminUserEditOneByIdInput {
  pb.resource.AdminUserVariable variable = 1;
  uint64 id = 2;
}

message AdminUserEditOneByIdOutput {}

message AdminUserRemoveOneByIdInput {
  uint64 id = 1;
}

message AdminUserRemoveOneByIdOutput {}

message AdminUserShowOnesByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 2;
  pb.resource.Pagination pagination = 3;
}

message AdminUserShowOnesByFiltersWithSortersPaginationOutput {
  repeated pb.resource.AdminUser admin_users = 1;
}

message AdminUserTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message AdminUserTotalByFiltersOutput {
  uint64 total = 1;
}



