syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service AppUserModel {
  rpc AddAppUser(AppUserAddOneInput) returns (AppUserAddOneOutput);
  rpc ShowOneByName(AppUserShowOneByNameInput) returns (AppUserShowOneByNameOutput);
  rpc ShowOneById(AppUserShowOneByIdInput) returns (AppUserShowOneByIdOutput);
  rpc IncreaseBalance(AppUserIncreaseBalanceInput) returns (AppUserIncreaseBalanceOutput);
}

message AppUserVariable {
  optional string name = 1;
  optional string password = 2;
}

message AppUserAddOneInput {
  AppUserVariable variable = 1;
}

message AppUserAddOneOutput {
  string name = 1;
}

message AppUserShowOneByNameInput {
  string name = 1;
}

message AppUserShowOneByNameOutput {
  pb.resource.AppUser app_user = 1;
}

message AppUserShowOneByIdInput {
  uint64 id = 1;
}

message AppUserShowOneByIdOutput {
  pb.resource.AppUser app_user = 1;
}

message AppUserIncreaseBalanceInput {
  uint64 id = 1;
  uint64 amount = 2;
}

message AppUserIncreaseBalanceOutput {
  bool status = 1;
}



