syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service GameModel {
  rpc AddOne(GameAddOneInput) returns (GameAddOneOutput);
  rpc ShowOneById(GameShowOneByIdInput) returns (GameShowOneByIdOutput);
  rpc ShowOneByKey(GameShowOneByKeyInput) returns (GameShowOneByKeyOutput);
  rpc ShowOnesByFiltersWithOrdersPagination(GameShowOnesByFiltersWithOrdersPaginationInput) returns (GameShowOnesByFiltersWithOrdersPaginationOutput);
  rpc EditOneById(GameEditOneByIdInput) returns (GameEditOneByIdOutput);
  rpc RemoveOneById(GameRemoveOneByIdInput) returns (GameRemoveOneByIdOutput);
  rpc TotalByFilters(GameTotalByFiltersInput) returns (GameTotalByFiltersOutput);
}

message GameVariable {
  optional uint64 game_type_id = 1;
  optional string key = 2;
  optional string name = 3;
  optional string description = 4;
}

message GameAddOneInput {
  GameVariable variable = 1;
}

message GameAddOneOutput {
  pb.resource.Game game = 1;
}

message GameShowOneByIdInput {
  uint64 id = 1;
}

message GameShowOneByIdOutput {
  pb.resource.Game game = 1;
}

message GameShowOneByKeyInput {
  string key = 1;
}

message GameShowOneByKeyOutput {
  pb.resource.Game game = 1;
}

message GameEditOneByIdInput {
  GameVariable variable = 1;
  uint32 id = 2;
}

message GameEditOneByIdOutput {
  bool status = 1;
}

message GameRemoveOneByIdInput {
  uint32 id = 1;
}

message GameRemoveOneByIdOutput {
  bool status = 1;
}

message GameShowOnesByFiltersWithOrdersPaginationInput {
  repeated pb.resource.Filter filters = 2;
  repeated pb.resource.Sorter sorters = 3;
  pb.resource.Pagination pagination = 1;
}

message GameShowOnesByFiltersWithOrdersPaginationOutput {
  repeated pb.resource.Game games = 1;
}

message GameTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTotalByFiltersOutput {
  uint64 total = 1;
}
