syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service GameTypeModel {
  rpc AddOne(GameTypeAddOneInput) returns (GameTypeAddOneOutput);
  rpc EditOneById(GameTypeEditOneByIdInput) returns (GameTypeEditOneByIdOutput);
  rpc RemoveOneById(GameTypeRemoveOneByIdInput) returns (GameTypeRemoveOneByIdOutput);
  rpc TotalByFilters(GameTypeTotalByFiltersInput) returns (GameTypeTotalByFiltersOutput);
}

message GameTypeAddOneInput {
  pb.resource.GameTypeValue value = 1;
}

message GameTypeAddOneOutput {
  pb.resource.GameType game_type = 1;
}

message GameTypeEditOneByIdInput {
  pb.resource.GameTypeValue value = 1;
  uint64 id = 2;
}

message GameTypeEditOneByIdOutput {}

// 數據模型直接對ID查找
message GameTypeRemoveOneByIdInput {
  uint64 id = 1;
}

message GameTypeRemoveOneByIdOutput {}

message GameTypeTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTypeTotalByFiltersOutput {
  uint64 total = 1;
}
