syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service GameModel {
  rpc AddOne(GameAddOneInput) returns (GameAddOneOutput);
  rpc ShowOneByKey(GameShowOneByKeyInput) returns (GameShowOneByKeyOutput);
  rpc EditOneById(GameEditOneByIdInput) returns (GameEditOneByIdOutput);
  rpc RemoveOneById(GameRemoveOneByIdInput) returns (GameRemoveOneByIdOutput);
  rpc TotalByFilters(GameTotalByFiltersInput) returns (GameTotalByFiltersOutput);
}

message GameValue {
  optional uint64 game_type_id = 1;
  optional string key = 2;
  optional string name = 3;
  optional string description = 4;
}

message GameAddOneInput {
  GameValue value = 1;
}

message GameAddOneOutput {
  pb.resource.Game game = 1;
}

message GameShowOneByKeyInput {
  string key = 1;
}

message GameShowOneByKeyOutput {
  pb.resource.Game game = 1;
}

message GameEditOneByIdInput {
  GameValue value = 1;
  uint64 id = 2;
}

message GameEditOneByIdOutput {
  bool status = 1;
}

message GameRemoveOneByIdInput {
  uint64 id = 1;
}

message GameRemoveOneByIdOutput {
  bool status = 1;
}

message GameTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTotalByFiltersOutput {
  uint64 total = 1;
}
