syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service GameModel {
  rpc AddOne(GameAddOneInput) returns (GameAddOneOutput);
  rpc ShowOneByKey(GameShowOneByKeyInput) returns (GameShowOneByKeyOutput);
  rpc EditOneById(GameEditOneByIdInput) returns (GameEditOneByIdOutput);
  rpc RemoveOneById(GameRemoveOneByIdInput) returns (GameRemoveOneByIdOutput);
  rpc TotalByFilters(GameTotalByFiltersInput) returns (GameTotalByFiltersOutput);
}

message GameAddOneInput {
  pb.resource.GameVariable variable = 1;
}

message GameAddOneOutput {
  pb.resource.Game game = 1;
}

message GameShowOneByKeyInput {
  string key = 1;
}

message GameShowOneByKeyOutput {
  pb.resource.Game game = 1;
}

message GameEditOneByIdInput {
  pb.resource.GameVariable variable = 1;
  uint64 id = 2;
}

message GameEditOneByIdOutput {}

message GameRemoveOneByIdInput {
  uint64 id = 1;
}

message GameRemoveOneByIdOutput {}

message GameTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTotalByFiltersOutput {
  uint64 total = 1;
}
