syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "google/protobuf/timestamp.proto";
import "resource/resource.proto";

service GameTypeModel {
  rpc AddOne(GameTypeAddOneInput) returns (GameTypeAddOneOutput);
  rpc ShowOneById(GameTypeShowOneByIdInput) returns (GameTypeShowOneByIdOutput);
  rpc ShowOnesByFiltersWithSortersPagination(GameTypeShowOnesByFiltersWithSortersPaginationInput) returns (GameTypeShowOnesByFiltersWithSortersPaginationOutput);
  rpc EditOneById(GameTypeEditOneByIdInput) returns (GameTypeEditOneByIdOutput);
  rpc RemoveOneById(GameTypeRemoveOneByIdInput) returns (GameTypeRemoveOneByIdOutput);
  rpc TotalByFilters(GameTypeTotalByFiltersInput) returns (GameTypeTotalByFiltersOutput);
}

message GameTypeAddOneInput {
  optional string key = 1;
  optional string name = 2;
}

message GameTypeAddOneOutput {
  uint32 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
}

message GameTypeShowOneByIdInput {
  uint32 id = 1;
}

message GameTypeShowOneByIdOutput {
  uint32 id = 1;
  string key = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  google.protobuf.Timestamp deleted_at = 6;
}

message GameTypeEditOneByIdInput {
  uint32 id = 1;
  optional string key = 2;
  optional string name = 3;
}

message GameTypeEditOneByIdOutput {
  bool status = 1;
}

message GameTypeRemoveOneByIdInput {
  uint32 id = 1;
}

message GameTypeRemoveOneByIdOutput {
  bool status = 1;
}

message GameTypeShowOnesByFiltersWithSortersPaginationInput {
  pb.resource.Pagination pagination = 1;
  repeated pb.resource.Filter filters = 2;
  repeated pb.resource.Sorter sorters = 3;
}

message GameTypeShowOnesByFiltersWithSortersPaginationOutput {
  repeated pb.resource.GameType game_types = 1;
}

message GameTypeTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTypeTotalByFiltersOutput {
  uint64 total = 1;
}
