syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service GameTypeModel {
  rpc AddOne(GameTypeAddOneInput) returns (GameTypeAddOneOutput);
  rpc ShowOneById(GameTypeShowOneByIdInput) returns (GameTypeShowOneByIdOutput);
  rpc ShowOnesByFiltersWithSortersPagination(GameTypeShowOnesByFiltersWithSortersPaginationInput) returns (GameTypeShowOnesByFiltersWithSortersPaginationOutput);
  rpc EditOneById(GameTypeEditOneByIdInput) returns (GameTypeEditOneByIdOutput);
  rpc RemoveOneById(GameTypeRemoveOneByIdInput) returns (GameTypeRemoveOneByIdOutput);
  rpc TotalByFilters(GameTypeTotalByFiltersInput) returns (GameTypeTotalByFiltersOutput);
}

message GameTypeVariable {
  optional string key = 1;
  optional string name = 2;
}

message GameTypeAddOneInput {
  GameTypeVariable variable = 1;
}

message GameTypeAddOneOutput {
  pb.resource.GameType game_type = 1;
}

message GameTypeShowOneByIdInput {
  uint32 id = 1;
}

message GameTypeShowOneByIdOutput {
  pb.resource.GameType game_type = 1;
}

message GameTypeEditOneByIdInput {
  GameTypeVariable variable = 1;
  uint32 id = 2;
}

message GameTypeEditOneByIdOutput {
  bool status = 1;
}

// 數據模型直接對ID查找
message GameTypeRemoveOneByIdInput {
  uint32 id = 1;
}

message GameTypeRemoveOneByIdOutput {
  bool status = 1;
}

message GameTypeShowOnesByFiltersWithSortersPaginationInput {
  pb.resource.Pagination pagination = 1;
  repeated pb.resource.Filter filters = 2;
  repeated pb.resource.Sorter sorters = 3;
}

message GameTypeShowOnesByFiltersWithSortersPaginationOutput {
  repeated pb.resource.GameType game_types = 1;
}

message GameTypeTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message GameTypeTotalByFiltersOutput {
  uint64 total = 1;
}
