syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "google/protobuf/timestamp.proto";
import "resource/common.proto";

service TableModel {
  rpc AddOne(TableAddOneInput) returns (TableAddOneOutput);
  rpc ShowOneById(TableShowOneByIdInput) returns (TableShowOneByIdOutput);
  rpc EditOneById(TableEditOneByIdInput) returns (TableEditOneByIdOutput);
  rpc RemoveOneById(TableRemoveOneByIdInput) returns (TableRemoveOneByIdOutput);
  rpc ShowOnesByFiltersWithSortersPagination(TableShowOnesByFiltersWithSortersPaginationInput) returns (TableShowOnesByFiltersWithSortersPaginationOutput);
  rpc TotalByFilters(TableTotalByFiltersInput) returns (TableTotalByFiltersOutput);
}

message TableVariable {
  optional string no = 1;
  optional uint64 game_id = 2;
  optional string key = 3;
  optional uint64 state = 4;
  optional string description = 5;
  optional string result = 6;
  google.protobuf.Timestamp started_at = 7;
  google.protobuf.Timestamp ended_at = 8;
}

message TableAddOneInput {
  TableVariable variable = 1;
}

message TableAddOneOutput {
  bool status = 1;
}

message TableShowOneByIdInput {
  uint64 id = 1;
}

message TableShowOneByIdOutput {
  pb.resource.Table table = 1;
}

message TableEditOneByIdInput {
  TableVariable variable = 1;
  uint64 id = 2;
}

message TableEditOneByIdOutput {
  bool status = 1;
}

message TableRemoveOneByIdInput {
  uint64 id = 1;
}

message TableRemoveOneByIdOutput {
  bool status = 1;
}

message TableShowOnesByFiltersWithSortersPaginationInput {
  repeated pb.resource.Filter filters = 1;
  repeated pb.resource.Sorter sorters = 3;
  pb.resource.Pagination pagination = 2;
}

message TableShowOnesByFiltersWithSortersPaginationOutput {
  repeated pb.resource.Table tables = 1;
}

message TableTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message TableTotalByFiltersOutput {
  uint64 total = 1;
}
