syntax = "proto3";

package pb.resource.model;

option go_package = "./pb_resource_model";

import "resource/common.proto";

service TableModel {
  rpc AddOne(TableAddOneInput) returns (TableAddOneOutput);
  rpc EditOneById(TableEditOneByIdInput) returns (TableEditOneByIdOutput);
  rpc RemoveOneById(TableRemoveOneByIdInput) returns (TableRemoveOneByIdOutput);
  rpc TotalByFilters(TableTotalByFiltersInput) returns (TableTotalByFiltersOutput);
}

message TableAddOneInput {
  pb.resource.TableValue value = 1;
}

message TableAddOneOutput {}

message TableEditOneByIdInput {
  pb.resource.TableValue value = 1;
  uint64 id = 2;
}

message TableEditOneByIdOutput {}

message TableRemoveOneByIdInput {
  uint64 id = 1;
}

message TableRemoveOneByIdOutput {}

message TableTotalByFiltersInput {
  repeated pb.resource.Filter filters = 1;
}

message TableTotalByFiltersOutput {
  uint64 total = 1;
}
